export const enumStatus = {
  "pending_approval": "Aprovação pendente",
  "refused": "Recusado",
  "expired": "Expirado - Pagamento não realizado",
  "finished": "Finalizado",
  "closed": "Encerrado",
  "approved": "Aprovado",
  "payment_pending": "Pagamento pendente",
  "cancelled": "Cancelado",
  "incomplete": "Incompleta",
  "refunded": "Reembolsado",
  "refund_solicitation": "Reembolso solicitado",
  "drawn": "Sorteado",
  "not_drawn": "Não sorteado",
  "awaiting_draw": "Aguardando sorteio",
  "awaiting_invites": "Aguardando convites",
}