export const enumRoutes = {
  "": "Início",
  "signin": "Entrar",
  "register": "Cadastrar",
  "associado": "Área do Associado",
  "home": "Início",
  "perfil": "Meu Perfil",
  "criar-reserva": "Criar Reserva",
  "enviar-documentos": "Enviar Documentos",
  "escolher-quarto": "Escolher Quarto",
  "finalizar-reserva": "Finalizar Reserva",
  "organizar-reserva": "Organizar Reserva",
  "solicitacao": "Solicitação",
  "sorteio": "Sorteio",
  "participar": "Participar",
  "acompanhantes": "Acompanhantes",
  "dependentes": "Dependentes",
  "convidados": "Convidados",
  "admin": "Administração",
  "associados": "Associados",
  "gerar-link": "Gerar Link",
  "aprovar-documentacao": "Aprovar Documentação",
  "enviar-aprovacao": "Enviar Aprovação",
  "enviar-recusa": "Enviar Recusa",
  "sistema": "Sistema",
  "configuracoes": "Configurações",
  "sorteios": "Sorteios",
  "inscritos": "Inscritos",
  "run": "Executar Sorteio",
  "inscricao": "Inscrição",
  "calendario": "Calendário",
  "criar-usuario": "Criar Usuário",
  "unauthorized": "Acesso Negado",
};
