export const rooms = [
  {
    number: 1,
    capacity: 6,
    floor: 0,
    preferential: true,
    partner_booking_fee_per_day: 45.00,
    contributor_booking_fee_per_day: 60.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 2,
    capacity: 6,
    floor: 0,
    preferential: true,
    partner_booking_fee_per_day: 45.00,
    contributor_booking_fee_per_day: 60.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 11,
    capacity: 4,
    floor: 1,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 12,
    capacity: 4,
    floor: 1,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 13,
    capacity: 4,
    floor: 1,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 14,
    capacity: 4,
    floor: 1,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 15,
    capacity: 4,
    floor: 1,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 16,
    capacity: 4,
    floor: 1,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 17,
    capacity: 4,
    floor: 1,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 18,
    capacity: 4,
    floor: 1,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 19,
    capacity: 4,
    floor: 1,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 21,
    capacity: 4,
    floor: 2,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 22,
    capacity: 4,
    floor: 2,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 23,
    capacity: 4,
    floor: 2,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 24,
    capacity: 4,
    floor: 2,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 25,
    capacity: 4,
    floor: 2,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 26,
    capacity: 4,
    floor: 2,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 27,
    capacity: 4,
    floor: 2,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 28,
    capacity: 6,
    floor: 2,
    preferential: false,
    partner_booking_fee_per_day: 45.00,
    contributor_booking_fee_per_day: 60.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 31,
    capacity: 4,
    floor: 3,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 32,
    capacity: 4,
    floor: 3,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 33,
    capacity: 4,
    floor: 3,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 34,
    capacity: 4,
    floor: 3,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 35,
    capacity: 4,
    floor: 3,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 36,
    capacity: 4,
    floor: 3,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 37,
    capacity: 4,
    floor: 3,
    preferential: false,
    partner_booking_fee_per_day: 25.00,
    contributor_booking_fee_per_day: 35.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
  {
    number: 38,
    capacity: 6,
    floor: 3,
    preferential: false,
    partner_booking_fee_per_day: 45.00,
    contributor_booking_fee_per_day: 60.00,
    partner_guest_fee_per_day: 40.00,
    contributor_guest_fee_per_day: 70.00,
  },
]